name: Python Packages Tests

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [ main ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build all packages
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel
  idf_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, release-v4.4]
    container: espressif/idf:${{ matrix.version }}
    steps:
      - name: workaround permission issue
        run: git config --global --add safe.directory /__w/clang-tidy-runner/clang-tidy-runner
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          repo=$(pwd)
          # the workflow may change a bit after idf.py pull this in
          cp ./pyclang/idf_extension.py $IDF_PATH/tools/idf_py_actions/temp_ext.py
          # use idf python env
          source $IDF_PATH/export.sh
          # install this package
          pip install -e ".[html]"
          # go to idf path and install the other stuffs
          cd $IDF_PATH
          idf_tools.py install xtensa-clang
          source ./export.sh
          wget https://raw.githubusercontent.com/espressif/llvm-project/xtensa_release_15.x/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
          chmod +x run-clang-tidy.py
        shell: bash
      - name: Test
        run: |
          cd $IDF_PATH
          source ./export.sh
          cd examples/get-started/hello_world
          idf.py clang-check --run-clang-tidy-py $IDF_PATH/run-clang-tidy.py
          idf.py clang-html-report
          # Regression tests
          idf.py clang-check --run-clang-tidy-py $IDF_PATH/run-clang-tidy.py --run-clang-tidy-options "-h"
          clang-tidy -dump-config >.clang-tidy
          idf.py clang-check --run-clang-tidy-py $IDF_PATH/run-clang-tidy.py --run-clang-tidy-options "-config-file .clang-tidy"
        shell: bash
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_logs
          path: /opt/esp/idf/examples/get-started/hello_world/
